# Symulacja MikroTik RB750Gr3 — SNMP v1/v2c
agentAddress  udp:161
rocommunity   public   default
rocommunity   private  default
sysDescr      MikroTik RouterOS 6.49.10 (stable) RB750Gr3
sysName       MikroTik-RB750
sysLocation   Server Room A / Rack 2
sysContact    admin@example.local
