# SNMP symulacja urzadzenia przemyslowego
# Wartosci nadpisywane przez env (PLC_SNMP_NAME, PLC_SNMP_DESCR, PLC_SNMP_LOC)
agentAddress udp:161
rocommunity  public  default
rocommunity  private default
sysDescr     ${PLC_SNMP_DESCR:-Siemens SIMATIC S7-1200 PLC}
sysName      ${PLC_SNMP_NAME:-PLC-1}
sysLocation  ${PLC_SNMP_LOC:-Hala produkcyjna A}
sysContact   automation@example.local
master agentx
