server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Symulacja Basic Auth dla testera naglowkow (www-authenticate)
    location /api/ {
        add_header WWW-Authenticate 'Basic realm="HMI API"';
        return 401;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
